// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StorageServices_UpdateCloudApprove_FullMethodName = "/storage.StorageServices/UpdateCloudApprove"
)

// StorageServicesClient is the client API for StorageServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServicesClient interface {
	UpdateCloudApprove(ctx context.Context, in *UpdateCloudApproveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type storageServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServicesClient(cc grpc.ClientConnInterface) StorageServicesClient {
	return &storageServicesClient{cc}
}

func (c *storageServicesClient) UpdateCloudApprove(ctx context.Context, in *UpdateCloudApproveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageServices_UpdateCloudApprove_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServicesServer is the server API for StorageServices service.
// All implementations should embed UnimplementedStorageServicesServer
// for forward compatibility
type StorageServicesServer interface {
	UpdateCloudApprove(context.Context, *UpdateCloudApproveRequest) (*emptypb.Empty, error)
}

// UnimplementedStorageServicesServer should be embedded to have forward compatible implementations.
type UnimplementedStorageServicesServer struct {
}

func (UnimplementedStorageServicesServer) UpdateCloudApprove(context.Context, *UpdateCloudApproveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCloudApprove not implemented")
}

// UnsafeStorageServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServicesServer will
// result in compilation errors.
type UnsafeStorageServicesServer interface {
	mustEmbedUnimplementedStorageServicesServer()
}

func RegisterStorageServicesServer(s grpc.ServiceRegistrar, srv StorageServicesServer) {
	s.RegisterService(&StorageServices_ServiceDesc, srv)
}

func _StorageServices_UpdateCloudApprove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCloudApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServicesServer).UpdateCloudApprove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageServices_UpdateCloudApprove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServicesServer).UpdateCloudApprove(ctx, req.(*UpdateCloudApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageServices_ServiceDesc is the grpc.ServiceDesc for StorageServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageServices",
	HandlerType: (*StorageServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCloudApprove",
			Handler:    _StorageServices_UpdateCloudApprove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/storage.proto",
}
