version: "3.7"

services:
  krakend_ce:
    container_name: arch_krakend_ce
    image: devopsfaith/krakend:watch
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - fake_api

  fake_api:
    container_name: arch_fake_api
    image: ghcr.io/lpereira/lwan:latest
    volumes:
      - ./data:/wwwroot
    ports:
      - "8000:8080"

  mongo:
    image: mongo:latest
    container_name: arch_mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  auth-go:
    container_name: arch_auth_go
    image: febrihidayan/go-architecture-monorepo/auth
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    environment:
      HTTP_PORT: ':8083'
      RPC_PORT: ':9083'
      USER_PORT: 'user-go:9084'
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_NAME: arch_auth
      MONGODB_HOST: 'mongo'
      MONGODB_PORT: '27017'
    ports:
      - '8083:8083'
      - '9083:9083'

  user-go:
    container_name: arch_user_go
    image: febrihidayan/go-architecture-monorepo/user
    build:
      context: .
      dockerfile: docker/user/Dockerfile
    environment:
      HTTP_PORT: ':8084'
      RPC_PORT: ':9084'
      AUTH_PORT: 'auth-go:9083'
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_NAME: arch_user
      MONGODB_HOST: 'mongo'
      MONGODB_PORT: '27017'
    ports:
      - '8084:8084'
      - '9084:9084'