// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthServices_CreateOrUpdateAuth_FullMethodName = "/auth.AuthServices/CreateOrUpdateAuth"
)

// AuthServicesClient is the client API for AuthServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServicesClient interface {
	CreateOrUpdateAuth(ctx context.Context, in *CreateOrUpdateAuthRequest, opts ...grpc.CallOption) (*CreateOrUpdateAuthResponse, error)
}

type authServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServicesClient(cc grpc.ClientConnInterface) AuthServicesClient {
	return &authServicesClient{cc}
}

func (c *authServicesClient) CreateOrUpdateAuth(ctx context.Context, in *CreateOrUpdateAuthRequest, opts ...grpc.CallOption) (*CreateOrUpdateAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateAuthResponse)
	err := c.cc.Invoke(ctx, AuthServices_CreateOrUpdateAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServicesServer is the server API for AuthServices service.
// All implementations should embed UnimplementedAuthServicesServer
// for forward compatibility.
type AuthServicesServer interface {
	CreateOrUpdateAuth(context.Context, *CreateOrUpdateAuthRequest) (*CreateOrUpdateAuthResponse, error)
}

// UnimplementedAuthServicesServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServicesServer struct{}

func (UnimplementedAuthServicesServer) CreateOrUpdateAuth(context.Context, *CreateOrUpdateAuthRequest) (*CreateOrUpdateAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateAuth not implemented")
}
func (UnimplementedAuthServicesServer) testEmbeddedByValue() {}

// UnsafeAuthServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServicesServer will
// result in compilation errors.
type UnsafeAuthServicesServer interface {
	mustEmbedUnimplementedAuthServicesServer()
}

func RegisterAuthServicesServer(s grpc.ServiceRegistrar, srv AuthServicesServer) {
	// If the following call pancis, it indicates UnimplementedAuthServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthServices_ServiceDesc, srv)
}

func _AuthServices_CreateOrUpdateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServicesServer).CreateOrUpdateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthServices_CreateOrUpdateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServicesServer).CreateOrUpdateAuth(ctx, req.(*CreateOrUpdateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthServices_ServiceDesc is the grpc.ServiceDesc for AuthServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthServices",
	HandlerType: (*AuthServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateAuth",
			Handler:    _AuthServices_CreateOrUpdateAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
